schemes:
  onehalf_dark: &onehalf_dark
    primary:
      background: '0x282c34'
      foreground: '0xdcdfe4'
  
    normal:
      black: '0x282c34'
      red: '0xe06c75'
      green: '0x98c379'
      yellow: '0xe5c07b'
      blue: '0x61afef'
      magenta: '0xc678dd'
      cyan: '0x56b6c2'
      white: '0xdcdfe4'
  
    bright:
      black: '0x282c34'
      red: '0xe06c75'
      green: '0x98c379'
      yellow: '0xe5c07b'
      blue: '0x61afef'
      magenta: '0xc678dd'
      cyan: '0x56b6c2'
      white: '0xdcdfe4'

  onehalf_light: &onehalf_light
    primary:
      background: '0xfafafa'
      foreground: '0x383a42'
  
    normal:
      black: '0x383a42'
      red: '0xe45649'
      green: '0x50a14f'
      yellow: '0xc18401'
      blue: '0x0184bc'
      magenta: '0xa626a4'
      cyan: '0x0997b3'
      white: '0xfafafa'
  
    bright:
      black: '0x383a42'
      red: '0xe45649'
      green: '0x50a14f'
      yellow: '0xc18401'
      blue: '0x0184bc'
      magenta: '0xa626a4'
      cyan: '0x0997b3'
      white: '0xfafafa'

  purify: &purify
    # Selection colors
    selection:
      text:       '0xFAFAFA'
      background: '0x252834'
    
    # Normal colors
    primary:
      background: '0x313440'
      foreground: '0xFAFAFA'
    normal:
      black:   '0x282C34'
      red:     '0xFF6059'
      green:   '0x5FFF87'
      yellow:  '0xFFFF87'
      blue:    '0x5FAFFF'
      magenta: '0xAF87FF'
      cyan:    '0x5FAFFF'
      white:   '0xFAFAFA'
    
    # Bright colors
    bright:
      black:   '0x282C34'
      red:     '0xFF6059'
      green:   '0x5FFF87'
      yellow:  '0xFFFF87'
      blue:    '0x5FAFFF'
      magenta: '0xAF87FF'
      cyan:    '0x5FAFFF'
      white:   '0xFAFAFA'

  dracula: &dracula
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'
      bright_foreground: '#ffffff'
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    search:
      matches:
        foreground: '#44475a'
        background: '#50fa7b'
      focused_match:
        foreground: '#44475a'
        background: '#ffb86c'
      bar:
        background: '#282a36'
        foreground: '#f8f8f2'
    hints:
      start:
        foreground: '#282a36'
        background: '#f1fa8c'
      end:
        foreground: '#f1fa8c'
        background: '#282a36'
    selection:
      text: CellForeground
      background: '#44475a'
    normal:
      black: '#21222c'
      red: '#ff5555'
      green: '#50fa7b'
      yellow: '#f1fa8c'
      blue: '#bd93f9'
      magenta: '#ff79c6'
      cyan: '#8be9fd'
      white: '#f8f8f2'
    bright:
      black: '#6272a4'
      red: '#ff6e6e'
      green: '#69ff94'
      yellow: '#ffffa5'
      blue: '#d6acff'
      magenta: '#ff92df'
      cyan: '#a4ffff'
      white: '#ffffff'

  google_light: &google_light
    # Default colors
    primary:
      background: '0xffffff'
      foreground: '0x373b41'
  
    # Normal colors
    normal:
      black:   '0x1d1f21'
      red:     '0xcc342b'
      green:   '0x198844'
      yellow:  '0xfba922'
      blue:    '0x3971ed'
      magenta: '0xa36ac7'
      cyan:    '0x3971ed'
      white:   '0xc5c8c6'
  
    # Bright colors
    bright:
      black:   '0x969896'
      red:     '0xcc342b'
      green:   '0x198844'
      yellow:  '0xfba922'
      blue:    '0x3971ed'
      magenta: '0xa36ac7'
      cyan:    '0x3971ed'
      white:   '0xffffff'
  
  google_dark: &google_dark
    # Default colors
    primary:
      background: '#1d1f21'
      foreground: '#c5c8c6'
  
    # Normal colors
    normal:
      black:   '#1d1f21'
      red:     '#cc342b'
      green:   '#198844'
      yellow:  '#fba922'
      blue:    '#3971ed'
      magenta: '#a36ac7'
      cyan:    '#3971ed'
      white:   '#c5c8c6'
  
    # Bright colors
    bright:
      black:   '#969896'
      red:     '#cc342b'
      green:   '#198844'
      yellow:  '#fba922'
      blue:    '#3971ed'
      magenta: '#a36ac7'
      cyan:    '#3971ed'
      white:   '#ffffff'
  ### Gruvbox###
  gruvbox_light: &gruvbox_light
    primary:
      # hard contrast: background = '#f9f5d7'
      #background: '#fbf1c7'
      background: '#f2e5bc'
      # soft contrast: background = '#f2e5bc'
      foreground: '#5c5856'
  
    # Normal colors
    normal:
      black:   '#fbf1c7'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#7c6f64'
  
    # Bright colors
    bright:
      black:   '#928374'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#3c3836'

  gruvbox_dark: &gruvbox_dark
    # Default colors
    primary:
      # hard contrast: background = '#1d2021'
      background: '#282828'
      # soft contrast: background = '#32302f'
      foreground: '#ebdbb2'

    # Normal colors
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'
  
  material: &material
  # Default colors
    primary:
      background: '#1e282d'
      foreground: '#c4c7d1'
  
    # Normal colors
    normal:
      black:   '#666666'
      red:     '#eb606b'
      green:   '#c3e88d'
      yellow:  '#f7eb95'
      blue:    '#80cbc4'
      magenta: '#ff2f90'
      cyan:    '#aeddff'
      white:   '#ffffff'
  
    # Bright colors
    bright:
      black:   '#ff262b'
      red:     '#eb606b'
      green:   '#c3e88d'
      yellow:  '#f7eb95'
      blue:    '#7dc6bf'
      magenta: '#6c71c4'
      cyan:    '#35434d'
      white:   '#ffffff'

  tokyo: &tokyo
    # Default colors
    primary:
      background: '#1a1b26'
      foreground: '#a9b1d6'
  
    # Normal colors
    normal:
      black:   '#32344a'
      red:     '#f7768e'
      green:   '#9ece6a'
      yellow:  '#e0af68'
      blue:    '#7aa2f7'
      magenta: '#ad8ee6'
      cyan:    '#449dab'
      white:   '#787c99'
  
    # Bright colors
    bright:
      black:   '#444b6a'
      red:     '#ff7a93'
      green:   '#b9f27c'
      yellow:  '#ff9e64'
      blue:    '#7da6ff'
      magenta: '#bb9af7'
      cyan:    '#0db9d7'
      white:   '#acb0d0'

  cyberpunk: &cyberpunk
    # Default colors
    primary:
      background: "#000b1e"
      foreground: "#0abdc6"
  
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text:   "#000b1e"
      cursor: "#0abdc6"
  
    # Normal colors
    normal:
      black:   "#123e7c"
      red:     "#ff0000"
      green:   "#d300c4"
      yellow:  "#f57800"
      blue:    "#123e7c"
      magenta: "#711c91"
      cyan:    "#0abdc6"
      white:   "#d7d7d5"
  
    # Bright colors
    bright:
      black:   "#1c61c2"
      red:     "#ff0000"
      green:   "#d300c4"
      yellow:  "#f57800"
      blue:    "#00ff00"
      magenta: "#711c91"
      cyan:    "#0abdc6"
      white:   "#d7d7d5" 

  dash: &dash
    # Default colors
    primary:
      background: '0x1c1c1c'
      foreground: '0xEDEFF0'
  
    # Normal colors
    normal:
      black:   '0x181b1d'
      red:     '0xd75f5f'
      green:   '0x87ff87'
      yellow:  '0xffaf5f'
      blue:    '0x87d7ff'
      magenta: '0xd787ff'
      cyan:    '0x00d7af'
      white:   '0x444444'
  
    # Bright colors
    bright:
      black:   '0xc9cccd'
      red:     '0xe05263'
      green:   '0x98d174'
      yellow:  '0xffb04b'
      blue:    '0x00a7f7'
      magenta: '0xad74d1'
      cyan:    '0x38dbc7'
      white:   '0xd1d6db'
# set color theme
# *google_dark
# *google_light
# *gruvbox_dark
# *gruvbox_light
# *dracula
# *material
# *tokyo
# *cyberpunk
# *onehalf_dark
# *onehalf_light
# *purify

colors: *dracula
